#!/usr/bin/env bash
# ^ Note the above "shebang" line. This says "This is an executable shell script"
# Name this script "pre-commit" and place it in the ".git/hooks/" directory

# If any command fails, exit immediately with that command's exit status
set -eo pipefail

api/vendor/bin/php-cs-fixer check --config api/.php-cs-fixer.dist.php --verbose --diff
echo "PHPCSFixer passed!"

api/vendor/bin/phpstan --memory-limit=1G --configuration=api/phpstan.dist.neon
echo "PHPStan passed!"